name: '🤖 Auto Copilot Review'

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize, edited]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue/PR number to review'
        required: false
        type: string

concurrency:
  group: '${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number || inputs.issue_number }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  auto-review:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5
    permissions:
      contents: 'read'
      issues: 'write'
      pull-requests: 'write'
    
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'

      - name: 'Auto-assign Copilot for review'
        uses: 'actions/github-script@v7'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            
            // Determinar se é issue ou PR
            const isIssue = context.eventName === 'issues' || context.payload.issue;
            const isPR = context.eventName === 'pull_request' || context.payload.pull_request;
            const number = context.payload.pull_request?.number || context.payload.issue?.number || context.payload.inputs?.issue_number;
            
            if (!number) {
              console.log('Nenhum número de issue/PR encontrado');
              return;
            }

            // Comentário padrão solicitando review do Copilot
            const reviewComment = `🤖 **Auto Review Request**

@Copilot, por favor, revise ${isIssue ? 'esta issue' : 'este pull request'} considerando:

${isPR ? `
- **Qualidade do código**: Verificar boas práticas, padrões e possíveis bugs
- **Segurança**: Identificar vulnerabilidades potenciais
- **Performance**: Sugerir otimizações quando necessário
- **Testes**: Avaliar cobertura e qualidade dos testes
- **Documentação**: Verificar se a documentação está adequada
` : `
- **Clareza**: A descrição está clara e completa?
- **Prioridade**: Qual a urgência desta tarefa?
- **Escopo**: O escopo está bem definido?
- **Dependências**: Existem dependências que devem ser consideradas?
- **Estimativa**: Qual a complexidade estimada?
`}

**Contexto adicional**: Esta é uma solicitação automática de review para garantir qualidade e consistência em nossos ${isIssue ? 'issues' : 'pull requests'}.

---
*Gerado automaticamente pelo xcloud-bot workflow*`;

            try {
              if (isPR) {
                // Para PRs, criar um review request
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: number,
                  reviewers: [], // Copilot não pode ser adicionado como reviewer tradicional
                });
                
                // Adicionar comentário no PR
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: number,
                  body: reviewComment
                });
                
                console.log(`✅ Review automático solicitado para PR #${number}`);
              } else {
                // Para issues, apenas comentar
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: number,
                  body: reviewComment
                });
                
                console.log(`✅ Review automático solicitado para Issue #${number}`);
              }
            } catch (error) {
              console.error('Erro ao solicitar review:', error);
              core.setFailed(`Falha ao solicitar review: ${error.message}`);
            }

      - name: 'Trigger Gemini Review (if PR)'
        if: github.event_name == 'pull_request'
        uses: ./.github/workflows/gemini-review.yml@main
        with:
          additional_context: 'Review automático solicitado via workflow auto-copilot-review'