name: '🏷️ Issue Management'

on:
  issues:
    types: [opened, edited, reopened, labeled, unlabeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Número da issue para processar'
        required: false
        type: string

concurrency:
  group: '${{ github.workflow }}-${{ github.event_name }}-${{ github.event.issue.number || inputs.issue_number || github.run_id }}'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  process-issue:
    name: 'Processar Issue'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      pull-requests: read
    
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Processar Issue'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number || inputs.issue_number }}
        run: |
          echo "🏷️ Processando issue #$ISSUE_NUMBER"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Author: ${{ github.event.issue.user.login }}"
          
          # Aqui você pode adicionar lógica específica de processamento
          # Por exemplo: análise de conteúdo, aplicação de labels, etc.
          
          echo "✅ Issue processada com sucesso"